server:
  port: 8088
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/statemachine?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  jpa:
    hibernate:
      ddl-auto: update
